Parse: update readings enc_key + rolling_code; Anpassung autocreate
viegener/Telegram-fhem pull request #6
Opened 2016-05-19 10:59 UTC by habeIchVergessen

2016-07-01 22:30 UTC, viegener commented
This is quite some extensive changes, and without explanation hard to assess. Can this be broken down into smaller pieces?

2016-07-02 09:25 UTC, habeIchVergessen commented on Somfy/10_SOMFY.pm
> +		return "Somfy RTS message format error (length)!" if (length($encData) != 14);
additional validation of received data

2016-07-02 09:27 UTC, habeIchVergessen commented on Somfy/10_SOMFY.pm
> +	# increment before sending
SOMFY_SendCommand: just changed the order of operation. don't increase enc key and rolling code in the end of last sending.

2016-07-02 09:32 UTC, habeIchVergessen commented on Somfy/10_SOMFY.pm
> +		# otherwise goto autocreate
slightly different handling for device detecting

2016-07-02 09:33 UTC, habeIchVergessen commented
added comments in view of changes

2016-11-07 19:29 UTC, viegener requested changes
I do not understand the reasoning for the change of order in operation, it would mean that now the reading rolling code will contain the latest (already used) rolling code and not the next one that will be used. Why is this needed to support Singalduino? It will affect existing users.

2016-11-08 09:14 UTC, habeIchVergessen commented
at least there is no difference between increasing rolling code + encryption key before or after sending.
for testing purpose i used a minuCUL for sending and received the message with signal duino in the same fhem instance. this constalation results in unchanged values, because the processing of received message decreasing rolling code and encryption key immediately.

2016-11-14 23:10 UTC, viegener commented
The problem is a different one - It is the issue that for existing users the behavior will be changed and the rolling code will not match anymore, since now the sematics of the current reading is changed.
The change seems required since the message received and the message sent are the same. I think there are three options: 
- Rolling_codes are not updated from parsed/received messages
- Rolling codes are increased by one when receiving a message in aprse function
- sent messages are put (via AddDuplicate) to the duplicate list and therefore ignored when receiving the same message 

The second solution would be least invasive and not changing existing behavior

2017-03-27 11:33 UTC, closed without merging